config/routes.rb
Rails.application.routes.draw do
	get 'messages' => 'messages#new'
	resources :messages
	root 'messages#new'
	post 'messages/api' => 'messages#api'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
require 'json'

class MessagesController < ApplicationController
	protect_from_forgery except: :api
	def new
	end
	def create
		@message = Message.new(params.require(:messages).permit(:text))
		@message.save
		url = "https://cipher-me.herokuapp.com/messages/" + @message.id.to_s
		render plain: url		
	end
	def show
		@message = Message.find(params[:id])
		@message.destroy
	end
	def api
		json = params.permit(:message)
		@message = Message.new
		@message.text = json
		@message.save
		url = "https://cipher-me.herokuapp.com/messages/" + @message.id.to_s
		url_json = {:url => url}  	
		render json: url_json.to_json
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CipherMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/create.html.erb
<%= link_to message_path(@message), message_path(@message) %>

app/views/messages/new.html.erb
<%= form_with scope: :messages, local: true do |form| %>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/messages/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>